#include "../../../Parsing/Keys.hpp"
#include "../../Mapping.hpp"
#include "../../Mappings.hpp"
#include "../../../Midi/MidiNote.hpp"

Mapping Mappings::Toontrack::getSuperiorDrummer3Mapping() {
    using namespace Keys;
    return Mapping("Toontrack Superior Drummer 3", {
        {Cymbal::Bell::China::_1, {{Note::C_SHARP, 7}}},
        {Cymbal::Bell::China::Tip::_1, {{Note::E, 7}}},
        {Cymbal::Hit::China::Bow::_1, {{Note::D_SHARP, 7}}},
        {Cymbal::Hit::China::Bow::Tip::_1, {{Note::C, 7}}},
        {Cymbal::Hit::China::_1, {{Note::E, 2}, {Note::D, 7}}},
        {Cymbal::Choke::China::_1, {{Note::F_SHARP, 2}, {Note::B, 6}}},
        {Cymbal::Bell::Crash::_1, {{Note::C_SHARP, 5}}},
        {Cymbal::Bell::Crash::Tip::_1, {{Note::E, 5}}},
        {Cymbal::Hit::Crash::Bow::_1, {{Note::D_SHARP, 5}}},
        {Cymbal::Hit::Crash::Bow::Tip::_1, {{Note::C, 5}}},
        {Cymbal::Hit::Crash::_1, {{Note::D, 5}}},
        {Cymbal::Choke::Crash::_1, {{Note::B, 4}}},
        {Cymbal::Bell::Crash::_2, {{Note::E, 0}, {Note::F_SHARP, 5}}},
        {Cymbal::Bell::Crash::Tip::_2, {{Note::A, 5}}},
        {Cymbal::Hit::Crash::Bow::_2, {{Note::G_SHARP, 5}}},
        {Cymbal::Hit::Crash::Bow::Tip::_2, {{Note::D_SHARP, 0}, {Note::F, 5}}},
        {Cymbal::Hit::Crash::_2, {{Note::C_SHARP, 2}, {Note::G, 5}}},
        {Cymbal::Choke::Crash::_2, {{Note::B, 4}, {Note::A_SHARP, 5}}},
        {Cymbal::Bell::Crash::_3, {{Note::C_SHARP, 6}}},
        {Cymbal::Bell::Crash::Tip::_3, {{Note::E, 6}}},
        {Cymbal::Hit::Crash::Bow::_3, {{Note::D_SHARP, 6}}},
        {Cymbal::Hit::Crash::Bow::Tip::_3, {{Note::C, 6}}},
        {Cymbal::Hit::Crash::_3, {{Note::G, 2}, {Note::D, 6}}},
        {Cymbal::Choke::Crash::_3, {{Note::G_SHARP, 2}, {Note::B, 5}}},
        {Cymbal::Bell::Crash::_4, {{Note::G_SHARP, 0}, {Note::F_SHARP, 6}}},
        {Cymbal::Bell::Crash::Tip::_4, {{Note::A, 6}}},
        {Cymbal::Hit::Crash::Bow::_4, {{Note::G_SHARP, 6}}},
        {Cymbal::Hit::Crash::Bow::Tip::_4, {{Note::G, 0}, {Note::F, 6}}},
        {Cymbal::Hit::Crash::_4, {{Note::A, 2}, {Note::G, 6}}},
        {Cymbal::Choke::Crash::_4, {{Note::A_SHARP, 2}, {Note::A_SHARP, 6}}},
        {Cymbal::Bell::Ride::_1, {{Note::F, 2}, {Note::F_SHARP, 7}}},
        {Cymbal::Bell::Ride::Tip::_1, {{Note::F_SHARP, 0}, {Note::A, 7}}},
        {Cymbal::Hit::Ride::Bow::_1, {{Note::F, 0}, {Note::G_SHARP, 7}}},
        {Cymbal::Hit::Ride::Bow::Tip::_1, {{Note::D_SHARP, 2}, {Note::F, 7}, {Note::E, 4}}},
        {Cymbal::Hit::Ride::Edge::_1, {{Note::B, 2}, {Note::G, 7}}},
        {Cymbal::Choke::Ride::_1, {{Note::A_SHARP, 7}}},

        {Tom::Hit::Floor::_1, {{Note::G, 1}}},
        {Tom::Rimshot::Floor::Rim::_1, {{Note::D, 4}}},
        {Tom::Rimshot::Floor::_1, {{Note::D_SHARP, 4}}},
        {Tom::Hit::Floor::_2, {{Note::F, 1}}},
        {Tom::Rimshot::Floor::Rim::_2, {{Note::C, 4}}},
        {Tom::Rimshot::Floor::_2, {{Note::C_SHARP, 4}}},
        {Tom::Hit::Rack::_1, {{Note::C, 2}}},
        {Tom::Rimshot::Rack::_1, {{Note::A, 4}}},
        {Tom::Rimshot::Rack::Rim::_1, {{Note::A_SHARP, 4}}},
        {Tom::Hit::Rack::_2, {{Note::A, 1}}},
        {Tom::Rimshot::Rack::_2, {{Note::F, 4}}},
        {Tom::Rimshot::Rack::Rim::_2, {{Note::F_SHARP, 4}}},

        {Hat::Closed::Bell::_1, {{Note::B, 7}}},
        {Hat::Closed::Edge::_1, {{Note::A_SHARP, -1}}},
        {Hat::Closed::Tip::_1, {{Note::C_SHARP, 3}, {Note::B, -1}, {Note::F_SHARP, 1}}},
        {Hat::Open::Bell::loose1, {{Note::C, 8}}},
        {Hat::Open::Edge::loose1, {{Note::E, 3}}},
        {Hat::Open::Tip::loose1, {{Note::C, -1}}},
        {Hat::Open::Bell::_0, {{Note::C_SHARP, 8}}},
        {Hat::Open::Edge::_0, {{Note::C, 0}}},
        {Hat::Open::Tip::_0, {{Note::C_SHARP, -1}}},
        {Hat::Open::Bell::_1, {{Note::D, 8}}},
        {Hat::Open::Edge::_1, {{Note::C_SHARP, 0}, {Note::A_SHARP, 1}}},
        {Hat::Open::Tip::_1, {{Note::D, -1}}},
        {Hat::Open::Bell::_2, {{Note::D_SHARP, 8}}},
        {Hat::Open::Edge::_2, {{Note::D, 0}}},
        {Hat::Open::Tip::_2, {{Note::D_SHARP, -1}}},
        {Hat::Open::Bell::_3, {{Note::E, 8}}},
        {Hat::Open::Edge::_3, {{Note::C, 3}}},
        {Hat::Open::Tip::_3, {{Note::E, -1}}},
        {Hat::Open::Tip::_4, {{Note::F, -1}}},
        {Hat::Closed::foot, {{Note::A, -1}}},
        {Hat::Open::pedal_splash, {{Note::B, -1}}},
        {Hat::Open::seq, {{Note::F, 3}}},
        {Hat::Closed::Edge::tight1, {{Note::D, 3}}},
        {Hat::Closed::Tip::tight1, {{Note::D_SHARP, 3}}},
        {Hat::Open::trigger, {{Note::G, -2}, {Note::F_SHARP, -1}, {Note::G_SHARP, -2}, {Note::G, -1}, {Note::A, -2}, {Note::G_SHARP, -1}}},

        {Kick::_1, {{Note::C, 1}, {Note::A_SHARP, 0}, {Note::B, 0}}},

        {Snare::Hit::flam, {{Note::A, 3}}},
        {Snare::Hit::_1, {{Note::D, 1}, {Note::F, 8}, {Note::G_SHARP, 3}, {Note::D_SHARP, 1}, {Note::A_SHARP, 3}}},
        {Snare::Alt::Side::_1, {{Note::A, 0}}},
        {Snare::Alt::Rim::_1, {{Note::B, 3}}},
        {Snare::Alt::Rim::Shot::_1, {{Note::E, 1}}},
        {Snare::Alt::Side::stick, {{Note::E, 4}, {Note::C_SHARP, 1}}}
    });
}